# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='entry_screen',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_action',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_value',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit_screen',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='language',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
